CREATE TABLE "dbo"."Event"
(
    "Id" int PRIMARY KEY IDENTITY,
    "Name" nvarchar(max),
    "Created" datetime,
    "Updated" datetime,
    "OwnerUserId" int REFERENCES "User"("Id"),
    "EventType" int,
    "Status" int,
    "SalaryStatus" int,
    "InvoiceHoogiaId" int,
    "InvoiceAddress" nvarchar(max),
    "InvoiceTag" nvarchar(max),
    "InvoiceNumber" nvarchar(max),
    "Note" nvarchar(max),
    "ReturnalNote" nvarchar(max),
    "PricePlan" int,
    "AccountKind" int,
    "Location" nvarchar(max),
    "ContactPersonName" nvarchar(max),
    "ContactPersonPhone" nvarchar(max),
    "ContactPersonEmail" nvarchar(max),
);
