# This is the deploy pipeline of Backstage2

image: atlassian/default-image:3

clone:
    depth: full

pipelines:
    branches:
        dev:
            - step:
                  name: 'Deployment to Heroku Stage Environment'
                  deployment: heroku-stage
                  script:
                      - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:main
        main:
            - step:
                  name: 'Deployment to Heroku Production Environment'
                  deployment: heroku-prod
                  script:
                      - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:main

    pull-requests:
        '**': #default
            - step:
                  name: Build
                  image: node:18
                  caches:
                      - node
                      - nextcache
                  script:
                      - yarn
                      - yarn build

definitions:
    caches:
        nextcache: .next/cache
