# This is the deploy pipeline of Backstage2

image: atlassian/default-image:3

clone:
    depth: full

pipelines:
    branches:
        dev:
            - step:
                  name: 'Deployment to Staging'
                  deployment: staging
                  script:
                      - pipe: atlassian/ssh-run:0.4.0
                        variables:
                            SSH_USER: $DEPLOY_USER
                            SERVER: $DEPLOY_SERVER
                            COMMAND: 'cd $BITBUCKET_REPO_SLUG && git fetch && git checkout $BITBUCKET_COMMIT && yarnpkg && yarnpkg build && sudo systemctl restart $DEPLOY_SERVICE'
                            # MODE: 'script' // If we want to have the command in a separate file
            - step:
                  name: 'Deployment to Heroku Stage Environment'
                  deployment: staging
                  script:
                      - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master

    pull-requests:
        '**': #default
            - step:
                  name: Build
                  image: node:16.13.1
                  caches:
                      - node
                      - nextcache
                  script:
                      - yarn
                      - yarn build

definitions:
    caches:
        nextcache: .next/cache
