#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Running pre-commit hook. Bypass with --no-verify."
echo "The hook formats staged files, compiles the project with Typescript and lints it with eslint."
yarn lint-staged
yarn tsc
yarn eslint .
