name: Yarn build

on:
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - run: corepack enable
            - uses: actions/setup-node@v4
              with:
                  node-version: 18.x
                  cache: 'yarn'
            - run: yarn
            - run: yarn build
